%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%;**     Method      :  Components_Init (component %DeviceType)
%;**     Description :
%;**         Initialization of components (with exception for Peripheral
%;**         Initialization Components which are initialized in 
%;**         Peripherals_Init() method).
%;**         For example, if automatic initialization feature 
%;**         is enabled in LDD component then its Init method call 
%;**         is executed in Components_Init() method.
%include Common\GeneralParametersNone.inc
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine