%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnTemperatureGet)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**       * sensor_index%Parsensor_index %>27 - 
%;**       * temperature%Partemperature %>27 - 
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine