%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ReadTemperature)
%;**     Description :
%;**         Read the temperature value from the sensor and stores it in
%;**         memory
%include Common\GeneralParameters.inc(27)
%;**       * sensor_index%Parsensor_index %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine