%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetTemperature)
%;**     Description :
%;**         Gets the temperature from memory.
%include Common\GeneralParameters.inc(27)
%;**       * sensor_index%Parsensor_index %>27 - Index of the sensor to
%;** %>29 get the temperature value.
%;**     Returns     :
%;**         ---%RetVal %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine