%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (f_setlabel)
%;**     Description :
%;**         Set Volume Label 
%include Common\GeneralParameters.inc(27)
%;**       * label%Parlabel %>27 - Pointer to the volume label to set
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine