%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnError)
%;**     Description :
%;**         Optional event hook called in error case
%include Common\GeneralParameters.inc(27)
%;**         errorNo%ParerrorNo %>27 - 
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine