%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (pcTimerGetTimerName)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         xTimer%ParxTimer %>27 - The handle of the timer being
%;** %>29 queried. 
%;**     Returns     :
%;**         ---%RetVal %>27 - A pointer to the timer's name, which is a
%;** %>29 standard NULL terminated C string. 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine