%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetButton)
%;**     Description :
%;**         Sets the status of a button
%include Common\GeneralParameters.inc(27)
%;**         button%Parbutton %>27 - Button control ID, starting with 0
%;**         isOn%ParisOn %>27 - If button is on or off
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine