%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetXY)
%;**     Description :
%;**         Set Joystick X and Y position
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - X position
%;**         y%Pary %>27 - Y position
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine