%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetThrottle)
%;**     Description :
%;**         Set Joystick throttle position
%include Common\GeneralParameters.inc(27)
%;**         throttle%Parthrottle %>27 - throttle position
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine