%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetHatPos)
%;**     Description :
%;**         Sets the hat switch position
%include Common\GeneralParameters.inc(27)
%;**         hat%Parhat %>27 - Hat control ID, starting with 0
%;**         position%Parposition %>27 - hat switch position
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine