%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%;**     Method      :  %1 (component %DeviceType)
%;**
%;**     Description :
%include Common\GeneralInternalDescription.prg (%1)
%;**         This method is internal. It is used by Processor Expert only.
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine