%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (TicksToTime)
%;**     Description :
%;**         Transforms ticks into time information
%include Common\GeneralParameters.inc(27)
%;**         ticks%Particks %>27 - 
%;**       * Time%ParTime %>27 - Pointer where to store the time
%;** %>29 information
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine