%ifndef CommentLine
%{ ###################################################################
%else CommentLine
%;** ###################################################################
%endif CommentLine
%if defined(DeviceType) & DeviceType<>'Events'
  %if defined(BeanGen_Preserve_User_Changes)
%;**     This component module is generated by the  tool with the option "Preserve User Changes".
%;**     IT'S NOT RECOMMENDED TO MODIFY IT, BUT THE TOOL ACCEPTS CHANGES IN THIS MODE.
  %else
%;**     This component module is generated by Processor Expert. Do not modify it.
  %endif
%endif
%;**     Filename    : %ModuleName.h
%if defined(CDEversion)
%;**     CDE edition : %CDEversion
%endif
%;**     Project     : %ProjectName
%;**     Processor   : %CPUvariant
%ifdef DeviceType
%;**     Component   : %DeviceType
%endif %- DeviceType
%if defined(BeanVersion)&defined(DriverVersion)
%if defined(CPU_DB_version)
%;**     Version     : Component %BeanVersion, Driver %DriverVersion, CPU db: %CPU_DB_version
%else %-defined(CPU_DB_version)
%;**     Version     : Component %BeanVersion, Driver %DriverVersion
%endif %-defined(CPU_DB_version)
%elif defined(BeanVersion)&ndefined(DriverVersion)
%;**     Version     : Component %BeanVersion
%elif ndefined(BeanVersion)&defined(DriverVersion)
%;**     Version     : Driver %DriverVersion
%elif ndefined(BeanVersion)&ndefined(DriverVersion)
%endif
%if defined(CPUmanualVersion)
%;**     Datasheet   : %CPUmanualVersion
%endif
%if defined(CompilerID)
%;**     Compiler    : %CompilerID
%else %- defined(CompilerID)
%if defined(PE_DEBUG)
%hint! Symbol 'CompilerID' is not defined! Please contact Marek Vinkler.
%endif
%endif %- defined(CompilerID)
%;**     Date/Time   : %TimeStamp
%;**     Abstract    :
%ifdef Abstract
%include %Abstract
%endif %- Abstract
%ifdef DriverNote
%;**     Driver      :
%for var from DriverNote
%;**         %var
%endfor %- var from DriverNote
%endif %- DriverNote
%ifdef Comment
%;**     Comment     :
%for var from Comment
%;**         %var
%endfor %- var from Comment
%endif %- Comment
%;**     Settings    :
%ifdef Settings
%include %Settings
%endif %- Settings
%;**     Contents    :
%if defined(ConstantList)|defined(MethodList)
%define! locFor 0
%for var from ConstantList
%if locFor <0 str_length(var)
%define! locFor %str_length(var)
%endif %- locFor <0 str_length(var)
%endfor %- var from ConstantList
%for var from MethodList
%if locFor <0 str_length(var)
%define! locFor %str_length(var)
%endif %- locFor <0 str_length(var)
%endfor %- var from MethodList
%:locFor+=12
%for var from ConstantList
%if var<>''
%;**         %var%>%locFor - %'%'var'_Hint'
%else %- var<>''
%;**
%endif %- var<>''
%endfor %- var from ConstantList
%if defined(ConstantList)&defined(MethodList)
%endif %- defined(ConstantList)&defined(MethodList)
%for var from MethodList
%if var<>''
  %ifdef %var
%;**         %'%var'%>%locFor - %'%'var'_Hint'
  %else
%;**         %var%>%locFor - %'%'var'_Hint'
  %endif
%else %- var<>''
%endif %- var<>''
%endfor %- var from MethodList
%else %- defined(ConstantList)|defined(MethodList)
%;**         No public methods
%endif %- defined(ConstantList)|defined(MethodList)
%;**
%include Common\HeaderCopyright.inc (%;**)
%ifndef CommentLine
%;** ###################################################################%}
%else CommentLine
%;** ###################################################################
%endif CommentLine
%-
%include Common\Header.doxy(%1,h)
%undef! locFor
%undef! var
