%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (UIDtoString)
%;**     Description :
%;**         Returns the value of the UID as string
%include Common\GeneralParameters.inc(27)
%;**         uid%Paruid %>27 - 
%;**       * buf%Parbuf %>27 - Pointer to 
%;**         bufSize%ParbufSize %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine