%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetPSP)
%;**     Description :
%;**         sets the process stack pointer
%include Common\GeneralParameters.inc(27)
%;**         setval%Parsetval %>27 - new PSP value
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine