%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (UIDSame)
%;**     Description :
%;**         Compares two UID
%include Common\GeneralParameters.inc(27)
%;**       * src%Parsrc %>27 - Pointer to 
%;**         Variable_1%ParVariable_1 %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - TRUE if the same, FALSE otherwise
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine