%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (InitCycleCounter)
%;**     Description :
%;**         Initializes the cycle counter, available if the core has a
%;**         DWT (Data Watchpoint and Trace) unit, usually present on
%;**         M3/M4/M7
%include Common\GeneralParametersNone.inc
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine