%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PutPixel)
%;**     Description :
%;**         Sets a pixel with a color
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - Pixel x coordinate
%;**         y%Pary %>27 - Pixel y coordinate
%;**         color%Parcolor %>27 - color of pixel
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine