%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ClearBuffer)
%;**     Description :
%;**         Clears the data buffer
%include Common\GeneralParameters.inc(27)
%;**         color%Parcolor %>27 - Color used for clearing
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine