%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnProgramEvent)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         key4%Parkey4 %>27 - Key to identify the source of the event
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine