%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (TargetSearch)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**         familyCode%ParfamilyCode %>27 - family code to restrict
%;** %>29 search for
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine