%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Search)
%;**     Description :
%;**         
%include Common\GeneralParameters.inc(27)
%;**       * newAddr%ParnewAddr %>27 - Pointer to 8 bytes of data where
%;** %>29 to store the new address
%;**         search_mode%Parsearch_mode %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - TRUE if new device has been found, FALSE
%;** %>29 otherwise.
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine