%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetBytes)
%;**     Description :
%;**         Gets multiple bytes from the bus
%include Common\GeneralParameters.inc(27)
%;**       * data%Pardata %>27 - 
%;**         count%Parcount %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine