%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ProgramEvent)
%;**     Description :
%;**         Used to add a program event
%include Common\GeneralParameters.inc(27)
%;**         key%Parkey %>27 - Key to identify the event, applies only if
%;** %>29 OnProgramEvent is enabled. (Valid range 0 -
%;** %>29 31)
%;**     Returns     :
%;**         ---%RetVal %>27 - error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine