%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (vTraceSetStopHook)
%;**     Description :
%;**         Sets a function to be called when the recorder is stopped.
%include Common\GeneralParameters.inc(27)
%;**         stopHookFunction%ParstopHookFunction %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine