%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SwapPins)
%;**     Description :
%;**         Swap the two pins
%include Common\GeneralParameters.inc(27)
%;**         swap%Parswap %>27 - if C1 and C2 pins shall be swapped.
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine