%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetPeriodUS)
%;**     Description :
%;**         Sets the timer period in microseconds
%include Common\GeneralParameters.inc(27)
%;**         us%Parus %>27 - number of microseconds
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine