%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetPeriodTicks)
%;**     Description :
%;**         Sets the timer period in ticks
%include Common\GeneralParameters.inc(27)
%;**         ticks%Particks %>27 - counter value
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine