%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (ErrorfTarget)
%;**     Description :
%;**         Prints an error string using printf() to the host which is
%;**         processed on the target
%include Common\GeneralParameters.inc(27)
%;**       * s%Pars %>27 - Pointer to string
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine