%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Write)
%;**     Description :
%;**         Write to buffer
%include Common\GeneralParameters.inc(27)
%;**         BufferIndex%ParBufferIndex %>27 - 
%;**       * pBuffer%ParpBuffer %>27 - Pointer to buffer
%;**         BufferSize%ParBufferSize %>27 - Size of buffer
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine