%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (EnableEvents)
%;**     Description :
%;**         Enables standard SystemView events to be generated.
%include Common\GeneralParameters.inc(27)
%;**         EnableMask%ParEnableMask %>27 - Events to be enabled
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine