%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (DisableEvents)
%;**     Description :
%;**         Disable standard SystemView events to not be generated.
%include Common\GeneralParameters.inc(27)
%;**         DisableMask%ParDisableMask %>27 - Events to be disabled.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine