%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (printfIO)
%;**     Description :
%;**         Printf() style function using XFormat component, using a
%;**         custom I/O handler.
%include Common\GeneralParameters.inc(27)
%;**       * io%Pario %>27 - Pointer to 
%;**         fmt%Parfmt %>27 - printf style format string
%;**     Returns     :
%;**         ---%RetVal %>27 - number of characters written
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine