%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (printf)
%;**     Description :
%;**         Printf() style function using XFormat component, using the
%;**         shell default I/O handler.
%include Common\GeneralParameters.inc(27)
%;**         fmt%Parfmt %>27 - printf style format string
%;**     Returns     :
%;**         ---%RetVal %>27 - number of characters written
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine