%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralEvent.inc (OnAfterIterateCmd)
%;**     Description :
%;**         Hook called after parsing a command in IterateTable().
%include Common\GeneralParameters.inc(27)
%;**         cmd%Parcmd %>27 - command parsed
%include Common\GeneralReturnNothing.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine