%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SendCharWithStdio)
%;**     Description :
%;**         Method to send a character using a standard I/O handle.
%include Common\GeneralParameters.inc(27)
%;**         ch%Parch %>27 - character to be sent
%;**         io%Pario %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine