%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (DrawPixel)
%;**     Description :
%;**         Draws a pixel
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - 
%;**         y%Pary %>27 - 
%;**         color%Parcolor %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine