%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (PutPixel)
%;**     Description :
%;**         Writes a pixel
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - 
%;**         y%Pary %>27 - 
%;**         color%Parcolor %>27 - 
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine