%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (DisplayOnOff)
%;**     Description :
%;**         Turns the display on or off
%include Common\GeneralParameters.inc(27)
%;**         on%Paron %>27 - TRUE to turn the display on, FALSE to turn
%;** %>29 it off
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine