%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetDeviceHandle)
%;**     Description :
%;**         Sets the HAL device handle.
%include Common\GeneralParameters.inc(27)
%;**         handle%Parhandle %>27 - Pointer to I2C_HandleTypeDef
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine