%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetIntegrationTime)
%;**     Description :
%;**         Sets the sensor integration time
%include Common\GeneralParameters.inc(27)
%;**         timing%Partiming %>27 - integration timing
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine