%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetForegroundColor)
%;**     Description :
%;**         Changes the header foreground color
%include Common\GeneralParameters.inc(27)
%;**       * header%Parheader %>27 - Pointer to header widget
%;**         color%Parcolor %>27 - background color
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine