%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetText)
%;**     Description :
%;**         Changes the header text
%include Common\GeneralParameters.inc(27)
%;**       * header%Parheader %>27 - Pointer to header widget
%;**       * text%Partext %>27 - Pointer to text
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine