%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Paint)
%;**     Description :
%;**         Paints a header in the window
%include Common\GeneralParameters.inc(27)
%;**       * header%Parheader %>27 - Pointer to widget
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine