%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetInsideColor)
%;**     Description :
%;**         Changes the inside color of an icon
%include Common\GeneralParameters.inc(27)
%;**       * icon%Paricon %>27 - Pointer to icon
%;**         color%Parcolor %>27 - foreground color
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine