%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetType)
%;**     Description :
%;**         Set the icon type
%include Common\GeneralParameters.inc(27)
%;**       * icon%Paricon %>27 - Pointer to icon
%;**         type%Partype %>27 - icon type
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine