%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SelectElement)
%;**     Description :
%;**         Selects an element in the window
%include Common\GeneralParameters.inc(27)
%;**       * element%Parelement %>27 - pointer to the element to select
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine