%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetSelectedElement)
%;**     Description :
%;**         Set the currently selected element
%include Common\GeneralParameters.inc(27)
%;**       * element%Parelement %>27 - Pointer to the element
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine