%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SetRoot)
%;**     Description :
%;**         Returns the UI root element. In case of a modal element,
%;**         this one is returned.
%include Common\GeneralParameters.inc(27)
%;**       * root%Parroot %>27 - Pointer to new root element
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine