%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Paint)
%;**     Description :
%;**         Paints the text to the screen
%include Common\GeneralParameters.inc(27)
%;**       * text%Partext %>27 - Pointer to element
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine