%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (randomSetSeed)
%;**     Description :
%;**         Sets a seed for the random number generator
%include Common\GeneralParameters.inc(27)
%;**         seed%Parseed %>27 - seed to be used for random number
%;** %>29 generator
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine