%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (map)
%;**     Description :
%;**         Maps a value from one range to another
%include Common\GeneralParameters.inc(27)
%;**         x%Parx %>27 - value to be mapped
%;**         in_min%Parin_min %>27 - input range minimum value
%;**         in_max%Parin_max %>27 - input range maximum value
%;**         out_min%Parout_min %>27 - output range maximum value
%;**         out_max%Parout_max %>27 - 
%;**     Returns     :
%;**         ---%RetVal %>27 - remapped value
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine