%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SkipSpaces)
%;**     Description :
%;**         Skips spaces
%include Common\GeneralParameters.inc(27)
%;**       * str%Parstr %>27 - Pointer to string to scan. Returns until
%;** %>29 where it has scanned.
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine