%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (MIDI_AllSoundOff)
%;**     Description :
%;**         Turns off all oscillators for the channel
%include Common\GeneralParameters.inc(27)
%;**         channel%Parchannel %>27 - Channel
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine