%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SendZeroes)
%;**     Description :
%;**         Sends a number of zeros
%include Common\GeneralParameters.inc(27)
%;**         nofZeros%ParnofZeros %>27 - Number of zeros to send
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine