%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (SendValues)
%;**     Description :
%;**         Sends a number of values
%include Common\GeneralParameters.inc(27)
%;**         nofValues%ParnofValues %>27 - Number of values to send
%;**         value%Parvalue %>27 - Values to send
%;**     Returns     :
%;**         ---%RetVal %>27 - Error code
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine