%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%;**     Method      :  ClearException (component ExceptionsHandler)
%;**     @brief
%;**         Clears the exception from the system.
%include Common\GeneralParameters.inc(27)
%;**         @return
%;**         void %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
