%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%;**     Method      :  GetException (component ExceptionsHandler)
%;**     @brief
%;**         Returns the catched exception.
%include Common\GeneralParameters.inc(27)
%;**         @return
%;**         Exception %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
