%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%;**     Method      :  throw (component ExceptionsHandler)
%;**     @brief
%;**         Throws an custom exception. Otherwise use an integer.
%include Common\GeneralParameters.inc(27)
%;**         @param
%;**         @return
%;**         void %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
